-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Dec 18, 2022 at 04:14 PM
-- Server version: 8.0.31-0ubuntu0.22.04.1
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `toucart_store`
--

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `slug`, `title`, `short_description`, `description`, `seo_keywords`, `seo_description`, `product_flag`, `image`, `price`, `sku`, `qty`, `vendor_id`, `status`, `featured`, `pending_for_approval`, `sort`, `shipment`, `deleted_at`, `created_at`, `updated_at`) VALUES
(1, '{\"ar\": \"بع-بالطريقة-التي-تشتري-بها\", \"en\": \"baa-baltryk-alty-tshtry-bha\"}', '{\"ar\": \"بع بالطريقة التي تشتري بها\", \"en\": \"بع بالطريقة التي تشتري بها\"}', '{\"ar\": \"دافيد فاغنر\", \"en\": \"دافيد فاغنر\"}', '{\"ar\": \"<p>نهج مبيعات حديث يؤتي ثماره ( حتي معك )</p>\", \"en\": \"<p>نهج مبيعات حديث يؤتي ثماره ( حتي معك )</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/nbH8Ec9knNMWw5in4Gd1bNQbXItEa4gvza9GSvHC.jpg', '6.000', 'dbr9W5', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 18:58:30', '2022-07-01 20:37:59'),
(2, '{\"ar\": \"على-خطى-الرسول\", \"en\": \"aal-kht-alrsol\"}', '{\"ar\": \"على خطى الرسول\", \"en\": \"على خطى الرسول\"}', '{\"ar\": \"ادهم شرقاوي\", \"en\": \"ادهم شرقاوي\"}', '{\"ar\": \"<p>هذا لأجلِ يوم نزول الوحيَ إذ لم أكنْ موجوداً لأضمَّكَ إلى قلبي وأنتَ ترتجف! ولأجلِ يوم الطائف إذ لم أكنْ موجوداً لأصدَّ عنكَ الحجارة بصدري! ولأجلِ يوم موت خديجة إذ لم أكنْ موجوداً لأمسحَ دمعتكَ، وأقول لكَ: أنا فِدى نعلكَ! ولأجلِ يوم أُحدٍ إذ لم أكنْ موجوداً وأنتَ تمسحُ الدّم عن وجهكَ الشريف لأقيكَ تلك الضّربة! ولأجلِ كتف الشاة المسمومة إذ لم أكن موجوداً لآكلها عنكَ! هذا لأجلِ أني آمنتُ بكَ ولم أرك، ولأجلِ أني صدّقتُكَ ولم أسمع منك، ولأجلِ أني أحببتُكَ ولم أُكحّلْ عينيَّ بكَ، بأبي أنتَ وأمي يا رسول الله ﷺ</p>\", \"en\": \"<p>هذا لأجلِ يوم نزول الوحيَ إذ لم أكنْ موجوداً لأضمَّكَ إلى قلبي وأنتَ ترتجف! ولأجلِ يوم الطائف إذ لم أكنْ موجوداً لأصدَّ عنكَ الحجارة بصدري! ولأجلِ يوم موت خديجة إذ لم أكنْ موجوداً لأمسحَ دمعتكَ، وأقول لكَ: أنا فِدى نعلكَ! ولأجلِ يوم أُحدٍ إذ لم أكنْ موجوداً وأنتَ تمسحُ الدّم عن وجهكَ الشريف لأقيكَ تلك الضّربة! ولأجلِ كتف الشاة المسمومة إذ لم أكن موجوداً لآكلها عنكَ! هذا لأجلِ أني آمنتُ بكَ ولم أرك، ولأجلِ أني صدّقتُكَ ولم أسمع منك، ولأجلِ أني أحببتُكَ ولم أُكحّلْ عينيَّ بكَ، بأبي أنتَ وأمي يا رسول الله ﷺ</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/b2AwpS9q5pLp0xlkqSUZo8Vxi7zxbvop1JtPVFna.jpg', '5.000', '03ntPX', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:00:31', '2022-07-01 20:39:49'),
(3, '{\"ar\": \"ارسم-لتربح\", \"en\": \"arsm-ltrbh\"}', '{\"ar\": \"ارسم لتربح\", \"en\": \"ارسم لتربح\"}', '{\"ar\": \"دان روم\", \"en\": \"دان روم\"}', '{\"ar\": \"<p>هذا الكتاب هو عبارة عن حلقة دراسية مكثفة حول كيفية&nbsp; القيادة ، والبيع ، والابتكار بإستخدام عقلك البصري&nbsp;</p>\", \"en\": \"<p>هذا الكتاب هو عبارة عن حلقة دراسية مكثفة حول كيفية&nbsp; القيادة ، والبيع ، والابتكار بإستخدام عقلك البصري&nbsp;</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/default.png', '6.000', '5iFeNc', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:03:46', '2022-07-01 20:40:16'),
(4, '{\"ar\": \"تهوي-ايه\", \"en\": \"thoy-ayh\"}', '{\"ar\": \"تهوي ايه\", \"en\": \"تهوي ايه\"}', '{\"ar\": \"بدرية البدري\", \"en\": \"بدرية البدري\"}', '{\"ar\": \"<p>نسا فى رغوة الشاي ابتسامتهُ</p>\", \"en\": \"<p>نسا فى رغوة الشاي ابتسامتهُ</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/default.png', '3.000', 'ND7y7V', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:05:54', '2022-07-01 20:39:18'),
(5, '{\"ar\": \"الثقافة-في-زمن-الجائحة\", \"en\": \"althkaf-fy-zmn-algayh\"}', '{\"ar\": \"الثقافة في زمن الجائحة\", \"en\": \"الثقافة في زمن الجائحة\"}', '{\"ar\": \"عبدالله البازعي\", \"en\": \"عبدالله البازعي\"}', '{\"ar\": \"<p>هى مقالات مترجمة كانت &nbsp;قد نشرت بغير العربية مابيت عامى 2020 و 2022 فى عدد كبير من المجلات و الصحف التى امتدت من الهند إلى امريكا ومن اوروبا إلى افريفيا .و تمثل المقالات على اختلافها لوناً من الترجمة غير شائع فى العالم العربى ، فهى تعرف القارئ على المشهد الثقافى فى العالم كما لا تعرف به الكتب المترجمة . إنها صورة حية للإنتاج الثقافى كما تنبض به المطبوعات الدورية التى لا تتوافر لكثير من القراء .</p>\", \"en\": \"<p>هى مقالات مترجمة كانت &nbsp;قد نشرت بغير العربية مابيت عامى 2020 و 2022 فى عدد كبير من المجلات و الصحف التى امتدت من الهند إلى امريكا ومن اوروبا إلى افريفيا .و تمثل المقالات على اختلافها لوناً من الترجمة غير شائع فى العالم العربى ، فهى تعرف القارئ على المشهد الثقافى فى العالم كما لا تعرف به الكتب المترجمة . إنها صورة حية للإنتاج الثقافى كما تنبض به المطبوعات الدورية التى لا تتوافر لكثير من القراء .</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/default.png', '4.000', 'jnDoa1', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:07:29', '2022-07-01 20:43:35'),
(6, '{\"ar\": \"انت-ايضا-صحابية\", \"en\": \"ant-ayda-shaby\"}', '{\"ar\": \"انت ايضا صحابية\", \"en\": \"انت ايضا صحابية\"}', '{\"ar\": \"ادهم شرقاوي\", \"en\": \"ادهم شرقاوي\"}', '{\"ar\": \"<p>أنتِ الحضن الحنون الذي نأوي إليه<br />هاربين من مشقة الحياة<br />وأنتِ الكتف الذي لا نستغني عن الاتكاء عليه رغم رقته!<br />وأنتِ العكاز الذي لا نستغني عن الاستناد عليه رغم نعومته!<br />وأنتِ مصنع الرجال ومهد الأبطال!<br />لستِ ضلعاً قاصراً أبداً<br />ولا مخلوقاً ضعيفاً يستحق الشفقة</p>\", \"en\": \"<p>أنتِ الحضن الحنون الذي نأوي إليه<br />هاربين من مشقة الحياة<br />وأنتِ الكتف الذي لا نستغني عن الاتكاء عليه رغم رقته!<br />وأنتِ العكاز الذي لا نستغني عن الاستناد عليه رغم نعومته!<br />وأنتِ مصنع الرجال ومهد الأبطال!<br />لستِ ضلعاً قاصراً أبداً<br />ولا مخلوقاً ضعيفاً يستحق الشفقة</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/default.png', '5.000', 'Rwoj8t', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:08:41', '2022-07-01 20:44:32'),
(7, '{\"ar\": \"كروت-تاملات-قرانية\", \"en\": \"krot-tamlat-krany\"}', '{\"ar\": \"كروت تاملات قرانية\", \"en\": \"كروت تاملات قرانية\"}', '{\"ar\": null}', '{\"ar\": \"<p>عدد 42 كارت من التأملات القرآنية</p>\\r\\n<p>(ونزعنا ما في صدورهم من غل)<br />عندما نطهر قلوبنا من الغل فنحن نعيش في نعيم يعيشه أهل الجنة.</p>\\r\\n<p><br />(ولقد نادانا نوح فلنعم المجيبون)</p>\\r\\n<p>عند حلول المصائب..اعرف من تنادي، فليس الكل يسمعك.</p>\", \"en\": \"<p>عدد 42 كارت من التأملات القرآنية</p>\\r\\n<p>(ونزعنا ما في صدورهم من غل)<br />عندما نطهر قلوبنا من الغل فنحن نعيش في نعيم يعيشه أهل الجنة.</p>\\r\\n<p><br />(ولقد نادانا نوح فلنعم المجيبون)</p>\\r\\n<p>عند حلول المصائب..اعرف من تنادي، فليس الكل يسمعك.</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/GLLlcWZGm11WYvSfYE0p5L1XByxAUSSuLZdkzvcS.jpg', '4.000', 'sPgMYN', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:09:57', '2022-07-01 20:44:49'),
(8, '{\"ar\": \"كروت-مع-القران\", \"en\": \"krot-maa-alkran\"}', '{\"ar\": \"كروت مع القران\", \"en\": \"كروت مع القران\"}', '{\"ar\": null}', '{\"ar\": \"<p>إِنَّ رَبِّي لَسَمِيعُ الدُّعَاءِ</p>\\r\\n<p>يا رب الامنيات والدعوات المرسلة</p>\\r\\n<p>ردها لنا غيثا مفرحا، اللهم دعوات قلبي</p>\\r\\n<p>اللهم إجابتك.</p>\", \"en\": \"<p>إِنَّ رَبِّي لَسَمِيعُ الدُّعَاءِ</p>\\r\\n<p>يا رب الامنيات والدعوات المرسلة</p>\\r\\n<p>ردها لنا غيثا مفرحا، اللهم دعوات قلبي</p>\\r\\n<p>اللهم إجابتك.</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/qiTZvZF9ZT3aKpXeHoRznnimEwn8lxRpsH1vxI5j.jpg', '4.000', 'bfsafb', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:10:52', '2022-07-01 20:28:45'),
(9, '{\"ar\": \"كروت-دعاء\", \"en\": \"krot-daaaaa\"}', '{\"ar\": \"كروت دعاء\", \"en\": \"كروت دعاء\"}', '{\"ar\": null}', '{\"ar\": \"<p>كروت دعاء <br />٥٠ كرت أدعية جميله مختلفه</p>\", \"en\": \"<p>كروت دعاء <br />٥٠ كرت أدعية جميله مختلفه</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/JOKjj5uoJ8zM2a1xVPLvTBA0KH6uCjQie6UpzJQM.jpg', '4.000', 'yEn119', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:11:30', '2022-07-01 20:28:21'),
(10, '{\"ar\": \"كروت-الحياة-تحبك\", \"en\": \"krot-alhya-thbk\"}', '{\"ar\": \"كروت الحياة تحبك\", \"en\": \"كروت الحياة تحبك\"}', '{\"ar\": null}', '{\"ar\": \"<p>عدد 50 كرت</p>\\r\\n<p>كروت الحياة تحبك</p>\", \"en\": \"<p>عدد 50 كرت</p>\\r\\n<p>كروت الحياة تحبك</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/7KXl3oO4q4Mxhwf6QE1hp5odkkh8w7YKvvkG3q1m.jpg', '4.000', 'UBQ1b9', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:12:26', '2022-07-01 20:27:43'),
(11, '{\"ar\": \"كروت-تفاءل\", \"en\": \"krot-tfaaal\"}', '{\"ar\": \"كروت تفاءل\", \"en\": \"كروت تفاءل\"}', '{\"ar\": null}', '{\"ar\": \"<p>عدد 50 كرت</p>\\r\\n<p>تفاءل</p>\\r\\n<p>سوف تفاجئك أقدار الله الجميلة</p>\\r\\n<p>تفاءل</p>\\r\\n<p>قد يؤخر الله الجميل ليجعله أجمل..</p>\", \"en\": \"<p>عدد 50 كرت</p>\\r\\n<p>تفاءل</p>\\r\\n<p>سوف تفاجئك أقدار الله الجميلة</p>\\r\\n<p>تفاءل</p>\\r\\n<p>قد يؤخر الله الجميل ليجعله أجمل..</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/uPriSJZftzOhEv5ks5GjM1YHYKL3Il4d1I733tR9.jpg', '4.000', 'h8IwWb', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:13:09', '2022-07-01 20:27:14'),
(12, '{\"ar\": \"كروت-اطمئن\", \"en\": \"krot-atmyn\"}', '{\"ar\": \"كروت اطمئن\", \"en\": \"كروت اطمئن\"}', '{\"en\": null}', '{\"ar\": \"<p>عدد 50 كرت</p>\\r\\n<p>عن الاطمئنان والسلام الداخلي</p>\\r\\n<p>وكيف تعيش الحياة بكل سعادة</p>\", \"en\": \"<p>عدد 50 كرت</p><p>عن الاطمئنان والسلام الداخلي</p><p>وكيف تعيش الحياة بكل سعادة</p>\"}', '{\"en\": null}', '{\"en\": null}', 'single', 'uploads/products/zWSEMZ6v3W8rjXuFaQhGxV2mBYbsGNPtt72X5uPJ.jpg', '4.000', 'a6ZlfL', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:13:59', '2022-10-23 22:45:13'),
(13, '{\"ar\": \"كروت-نزار-قباني\", \"en\": \"krot-nzar-kbany\"}', '{\"ar\": \"كروت نزار قباني\", \"en\": \"كروت نزار قباني\"}', '{\"ar\": null}', '{\"ar\": \"<p>يحتوي البوكس علي 50 كرت</p>\\r\\n<p>الكروت تحتوي افضل كلمات الشاعر والكاتب نزار القباني</p>\", \"en\": \"<p>يحتوي البوكس علي 50 كرت</p>\\r\\n<p>الكروت تحتوي افضل كلمات الشاعر والكاتب نزار القباني</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/Q4vvInMb7GMlf1697JfyFszmPhMb5VILEjmCpNpH.jpg', '4.000', '90lpur', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:14:46', '2022-07-01 20:25:56'),
(14, '{\"ar\": \"كروت-امي-العزيزة\", \"en\": \"krot-amy-alaazyz\"}', '{\"ar\": \"كروت امي العزيزة\", \"en\": \"كروت امي العزيزة\"}', '{\"ar\": null}', '{\"ar\": \"<p>يحتوي البوكس علي 50 كارت</p>\\r\\n<p>الكروت تحتوي علي اجمل العبارات عن الام</p>\", \"en\": \"<p>يحتوي البوكس علي 50 كارت</p>\\r\\n<p>الكروت تحتوي علي اجمل العبارات عن الام</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/vEXliAMjFW3WE0odyKqpIUK1tuOZ1f4ikTd0i9Op.jpg', '4.000', 'mXA1fC', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:15:36', '2022-07-01 20:25:27'),
(15, '{\"ar\": \"كروت-محمود-درويش\", \"en\": \"krot-mhmod-droysh\"}', '{\"ar\": \"كروت محمود درويش\", \"en\": \"كروت محمود درويش\"}', '{\"ar\": null}', '{\"ar\": \"<p>يحتوي البوكس علي 50 كرت</p>\\r\\n<p>الكروت تحتوي افضل كلمات الشاعر محمود درويش</p>\", \"en\": \"<p>يحتوي البوكس علي 50 كرت</p>\\r\\n<p>الكروت تحتوي افضل كلمات الشاعر محمود درويش</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/JX6q6jZfUFNB8JMUSuzCjHwIyJL5ogKkNhjdkEIn.jpg', '4.000', 'gD4dHN', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:16:17', '2022-07-01 20:24:54'),
(16, '{\"ar\": \"كروت-جبران-خليل-جبران\", \"en\": \"krot-gbran-khlyl-gbran\"}', '{\"ar\": \"كروت جبران خليل جبران\", \"en\": \"كروت جبران خليل جبران\"}', '{\"ar\": null}', '{\"ar\": \"<p>يحتوي البوكس على 50 كارت</p>\\r\\n<p>من افضل عبارات الكاتب جبران خليل جبران</p>\", \"en\": \"<p>يحتوي البوكس على 50 كارت</p>\\r\\n<p>من افضل عبارات الكاتب جبران خليل جبران</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/IdcQ3F60X2jUANGwrTzmRzcBBkcq9Vnesl5d7api.jpg', '4.000', 'FPkvQd', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:16:57', '2022-07-01 20:24:19'),
(17, '{\"ar\": \"كروت-جلال-الدين-الرومي\", \"en\": \"krot-glal-aldyn-alromy\"}', '{\"ar\": \"كروت جلال الدين الرومي\", \"en\": \"كروت جلال الدين الرومي\"}', '{\"ar\": null}', '{\"ar\": \"<p>يحتوي البوكس على 50 كارت من افضل عبارات الكاتب جلال الدين الرومي</p>\\r\\n<p>&nbsp;</p>\", \"en\": \"<p>يحتوي البوكس على 50 كارت من افضل عبارات الكاتب جلال الدين الرومي</p>\\r\\n<p>&nbsp;</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/default.png', '4.000', 'kGsrUF', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-25 19:17:53', '2022-07-01 20:23:43'),
(18, '{\"ar\": \"مجموعة-التخرج\", \"en\": \"graduation-collection\"}', '{\"ar\": \"مجموعة التخرج\", \"en\": \"Graduation collection\"}', '{\"ar\": null}', '{\"ar\": \"<p>فازة رمادية،</p>\\r\\n<p>تحتوي على نوعين من الوزر بالإضافو للبالون</p>\", \"en\": \"<p>Gray Vase&nbsp;</p>\\r\\n<p>contain of two kinds of flower and balloon&nbsp;</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/llk2E133w8jgi7bpIR8XPBq2LZxguNdQoFYKFioO.jpg', '27.500', 'GNVJ2TVI', 46, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-29 20:02:17', '2022-11-24 00:27:03'),
(19, '{\"ar\": \"مجموعة-التخرج-1\", \"en\": \"graduation-collection-1\"}', '{\"ar\": \"مجموعة التخرج\", \"en\": \"Graduation collection\"}', '{\"ar\": null}', '{\"ar\": \"<p>إطار أسود مع ورد و عبارة تخرج</p>\", \"en\": \"<p>Black frame with flower and a congratulations statement&nbsp;</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/kypxoWqZPFGUhC1dMrmjrLcq7j4GGtejp1X8itMd.jpg', '25.000', '80JVQLXK', 100, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-29 20:05:10', '2022-07-02 20:46:02'),
(20, '{\"ar\": \"بوكيه-البيونيا\", \"en\": \"peonia-bouquet\"}', '{\"ar\": \"بوكيه البيونيا\", \"en\": \"Peonia bouquet\"}', '{\"ar\": null}', '{\"ar\": \"<p>ورد البيونيا مع أنواع ورد مختلفه</p>\\r\\n<p>&nbsp;</p>\\r\\n<p>ألوان البوكيه قابله للتغير حسب التوفر&nbsp;</p>\", \"en\": \"<p>Peonia flower with mix flower&nbsp;</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/fTtFBwqXR0n7BVEvZtG4UcKFVv025YjClTp1rCMi.jpg', '21.500', 'YUJODJJT', NULL, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-06-29 20:12:21', '2022-07-02 20:45:52'),
(21, '{\"ar\": \"تعليقة-زيونة-ميني-سماوي\", \"en\": \"hanger-zayona-mini-blue-sky\"}', '{\"ar\": \"تعليقة - زيونة ميني -سماوي\", \"en\": \"Hanger - Zayona mini - Blue sky\"}', '{\"ar\": null}', '{\"ar\": \"<p><strong><u>الطول</u></strong><strong><u> :</u></strong> 9 سم</p>\\r\\n<p><strong><u>الخيط المستخدم</u></strong><strong><u> :</u></strong> قطن</p>\\r\\n<p><strong><u>السعر يتضمن</u></strong><strong><u> :</u></strong> حبل تعليق - ميدالية - مخيط وراها بروش - كيس قطني صغير</p>\\r\\n<p>* تعليقة سيارة - تعليقة جنطة - ميدالية - بروشة - قلادة&nbsp;</p>\", \"en\": \"<p><strong><u>Height :</u></strong> 9 cm</p>\\r\\n<p><strong><u>Material:</u></strong> Cotton</p>\\r\\n<p><strong><u>Price includes :</u></strong> Hanger rope , Keychain, Brooch and Small Cotton Bag</p>\\r\\n<p>* Car mirror hanger, Bag hanger , Keychain, Brooch</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/oLGhmAvq2cEIZnsq0Og4Rhc9aT3USUpLctOnbeZg.jpg', '6.500', 'MAWKWL6A', 20, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-07-03 19:19:04', '2022-07-03 19:19:04'),
(22, '{\"ar\": \"تعليقة-زيونة-ميني-أصفر\", \"en\": \"hanger-zayona-mini-yellow\"}', '{\"ar\": \"تعليقة - زيونة ميني  - أصفر\", \"en\": \"Hanger - Zayona mini  - Yellow\"}', '{\"ar\": null}', '{\"ar\": \"<p><strong><u>الطول</u></strong><strong><u> :</u></strong> 9 سم</p>\\r\\n<p><strong><u>الخيط المستخدم</u></strong><strong><u> :</u></strong> قطن</p>\\r\\n<p><strong><u>السعر يتضمن</u></strong><strong><u> :</u></strong> حبل تعليق - ميدالية - مخيط وراها بروش - كيس قطني صغير</p>\\r\\n<p>* تعليقة سيارة - تعليقة جنطة - ميدالية - بروشة - قلادة&nbsp;</p>\", \"en\": \"<p><strong><u>Height :</u></strong> 9 cm</p>\\r\\n<p><strong><u>Material:</u></strong> Cotton</p>\\r\\n<p><strong><u>Price includes :</u></strong> Hanger rope , Keychain, Brooch and Small Cotton Bag</p>\\r\\n<p>* Car mirror hanger, Bag hanger , Keychain, Brooch</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/dQlGF3Y9QtwuRzn1UvcbqrJvR3BEFExGufW5GwDq.jpg', '6.500', 'SKTRLM1E', 20, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-07-03 19:20:48', '2022-07-03 19:20:48'),
(23, '{\"ar\": \"تعليقة-زيونة-ميني-وردي\", \"en\": \"hanger-zayona-mini-pink\"}', '{\"ar\": \"تعليقة - زيونة ميني  - وردي\", \"en\": \"Hanger - Zayona mini  - Pink\"}', '{\"ar\": null}', '{\"ar\": \"<p><strong><u>الطول</u></strong><strong><u> :</u></strong> 9 سم</p>\\r\\n<p><strong><u>الخيط المستخدم</u></strong><strong><u> :</u></strong> قطن</p>\\r\\n<p><strong><u>السعر يتضمن</u></strong><strong><u> :</u></strong> حبل تعليق - ميدالية - مخيط وراها بروش - كيس قطني صغير</p>\\r\\n<p>* تعليقة سيارة - تعليقة جنطة - ميدالية - بروشة - قلادة&nbsp;</p>\", \"en\": \"<p><strong><u>Height :</u></strong> 9 cm</p>\\r\\n<p><strong><u>Material:</u></strong> Cotton</p>\\r\\n<p><strong><u>Price includes :</u></strong> Hanger rope , Keychain, Brooch and Small Cotton Bag</p>\\r\\n<p>* Car mirror hanger, Bag hanger , Keychain, Brooch</p>\"}', '{\"ar\": null}', '{\"ar\": null}', 'single', 'uploads/products/ILKSUvgyhZqpxA73tK0Vhqxb91UQU2Ejkq4Y0Uis.jpg', '6.500', 'BNFZOPNZ', 19, 1, 1, 0, 1, 0, '{\"weight\":null,\"width\":null,\"length\":null,\"height\":null}', NULL, '2022-07-03 19:22:48', '2022-11-17 02:50:33');

--
-- Dumping data for table `product_categories`
--

INSERT INTO `product_categories` (`id`, `category_id`, `product_id`, `created_at`, `updated_at`) VALUES
(1, 9, 1, NULL, NULL),
(2, 8, 2, NULL, NULL),
(3, 7, 3, NULL, NULL),
(4, 10, 4, NULL, NULL),
(5, 9, 5, NULL, NULL),
(6, 9, 6, NULL, NULL),
(7, 3, 7, NULL, NULL),
(8, 3, 8, NULL, NULL),
(9, 3, 9, NULL, NULL),
(10, 3, 10, NULL, NULL),
(11, 3, 11, NULL, NULL),
(12, 3, 12, NULL, NULL),
(13, 3, 13, NULL, NULL),
(14, 3, 14, NULL, NULL),
(15, 3, 15, NULL, NULL),
(16, 3, 16, NULL, NULL),
(17, 3, 17, NULL, NULL),
(18, 6, 18, NULL, NULL),
(19, 6, 19, NULL, NULL),
(20, 2, 20, NULL, NULL),
(21, 5, 21, NULL, NULL),
(22, 1, 21, NULL, NULL),
(23, 5, 22, NULL, NULL),
(24, 4, 22, NULL, NULL),
(25, 5, 23, NULL, NULL),
(26, 1, 23, NULL, NULL);

COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
